project:
  type: website

website:
  title: "Alina Schneider"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about-me.qmd
        text: About Me
      - href: CV.qmd
        text: Curriculum Vitae
      - href: works.qmd
        text: Works
      

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true



